# Generated by Django 5.2.4 on 2025-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='building_number',
            field=models.CharField(default='Not provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default='No', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='society',
            field=models.CharField(default='No', max_length=200),
            preserve_default=False,
        ),
    ]
