# Generated by Django 5.2.4 on 2025-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_profile_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('celebration', 'Celebration'), ('grievance', 'Grievance'), ('information', 'Information'), ('invitation', 'Invitation'), ('safety', 'Safety & Security'), ('maintenance', 'Maintenance'), ('event', 'Event'), ('announcement', 'Announcement'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('emergency', 'Emergency'), ('lost_found', 'Lost & Found'), ('other', 'Other')], default='information', max_length=20),
        ),
    ]
