# Generated by Django 5.2.4 on 2025-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('rwa_member', 'RWA Member')], default='resident', max_length=20),
        ),
    ]
